# Generated by Django 4.2.6 on 2023-11-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
